---
- hosts: master
  gather_facts: no
  vars:
    home: /root
    istio_dir: "{{ home }}/istio-1.0.2"
    istioctl: "{{ istio_dir }}/bin/istioctl"
    tutorial_dir: "{{ home }}/istio-tutorial"
    customer_dir: "{{ tutorial_dir }}/customer/java/springboot/"
    recommendation_dir: "{{ tutorial_dir }}/recommendation/java/vertx"
    preference_dir: "{{ tutorial_dir }}/preference/java/springboot"
    oc: "/usr/bin/oc"
    mvn: "{{ home }}/apache-maven-3.5.4/bin/mvn"
    docker: "/bin/docker"
  tasks:
    - name: Enable mutual tls
      shell: |
        {{ istioctl }} create -f istiofiles/authentication-enable-tls.yml 
        {{ istioctl }} create -f istiofiles/destination-rule-tls.yml
      args:
        chdir: '{{ tutorial_dir }}'
      register: tls_reg

    - debug:
        var: tls_reg
