---
- hosts: master
  gather_facts: no
  vars:
    home: /root
    istio_dir: "{{ home }}/istio-1.0.2"
    istioctl: "{{ istio_dir }}/bin/istioctl"
    tutorial_dir: "{{ home }}/istio-tutorial"
    customer_dir: "{{ tutorial_dir }}/customer/java/springboot/"
    recommendation_dir: "{{ tutorial_dir }}/recommendation/java/vertx"
    preference_dir: "{{ tutorial_dir }}/preference/java/springboot"
    oc: "/usr/bin/oc"
    mvn: "{{ home }}/apache-maven-3.5.4/bin/mvn"
    docker: "/bin/docker"
  tasks:
    - shell: ifconfig $(route |grep default|awk '{print $8}')|grep "inet "|awk '{print $2}'
      register: ip_reg
       
    - set_fact:
        ip_address: '{{ ip_reg.stdout }}'

    - set_fact:
        gateway_url: 'http://{{ ip_address }}'

    - debug:
        var: gateway_url

