---
- hosts: master
  gather_facts: yes
  vars:
    home: /root
    istio_dir: "{{ home }}/istio-1.0.2"
    istioctl: "{{ istio_dir }}/bin/istioctl"
    tutorial_dir: "{{ home }}/istio-tutorial"
    customer_dir: "{{ tutorial_dir }}/customer/java/springboot/"
    recommendation_dir: "{{ tutorial_dir }}/recommendation/java/vertx"
    preference_dir: "{{ tutorial_dir }}/preference/java/springboot"
    oc: "/usr/bin/oc"
    mvn: "{{ home }}/apache-maven-3.5.4/bin/mvn"
    docker: "/bin/docker"
  tasks:
    - name: Introduce timeout to recommendation v2
      lineinfile:
        path: '{{ recommendation_dir }}/src/main/java/com/redhat/developer/demos/recommendation/RecommendationVerticle.java'
        regexp: '//        router.get\("/"\).handler\(this::timeout\);'
        line: '        router.get("/").handler(this::timeout);'
        state: present

    - name: Build Recommendation
      command: "{{ mvn }} clean package"
      args:
        chdir: "{{ recommendation_dir }}"

    - name: Build recommendation docker image
      command: "{{ docker }} build -t example/recommendation:v2 ."
      args:
        chdir: "{{ recommendation_dir }}"

    - name: Delete old pod
      command: '{{ oc }} delete pod -l app=recommendation,version=v2'

    - name: Create destinationrule and virtualservice
      shell: |
        {{ istioctl }} create -f istiofiles/destination-rule-recommendation-v1-v2.yml -n tutorial
        {{ istioctl }} create -f istiofiles/virtual-service-recommendation-v1_and_v2_50_50.yml -n tutorial
      args:
        chdir: '{{ tutorial_dir }}'
