---
- hosts: master
  vars:
    home: /root
    istio_dir: "{{ home }}/istio-1.0.2"
    istioctl: "{{ istio_dir }}/bin/istioctl"
    tutorial_dir: "{{ home }}/istio-tutorial"
    customer_dir: "{{ tutorial_dir }}/customer/java/springboot/"
    recommendation_dir: "{{ tutorial_dir }}/recommendation/java/vertx"
    preference_dir: "{{ tutorial_dir }}/preference/java/springboot"
    oc: "/usr/bin/oc"
    mvn: "{{ home }}/apache-maven-3.5.4/bin/mvn"
    docker: "/bin/docker"
  tasks:
    - name: Create version 2
      lineinfile:
        path: '{{ recommendation_dir }}/src/main/java/com/redhat/developer/demos/recommendation/RecommendationVerticle.java'
        regexp: '^(.*)recommendation v. from(.*)$'
        line: '\1recommendation v1 from\2'
        backrefs: yes

    - name: 
      command: "{{ mvn }} clean package"
      args:
        chdir: "{{ recommendation_dir }}"

    - name: Build docker image
      command: "{{ docker }} build -t example/recommendation:v1 ."
      args:
        chdir: "{{ recommendation_dir }}"
    
    - name: Create the deployment
      shell: "{{ istioctl }} kube-inject -f ../../kubernetes/Deployment.yml| /bin/sed 's/- NET_ADMIN/- NET_ADMIN\\n          privileged: true\\n/g'| {{ oc }} apply -n tutorial -f -"
      args:
        chdir: "{{ recommendation_dir }}" 

    - name: Delete old pod
      command: '{{ oc }} delete pod -l app=recommendation,version=v1'

