---
- hosts: master
  gather_facts: yes
  vars:
    home: "{{ hostvars['localhost']['ansible_facts']['env']['HOME'] }}"
    istio_dir: "{{ home }}/istio-1.0.2"
    istioctl: "{{ istio_dir }}/bin/istioctl"
    tutorial_dir: "{{ home }}/istio-tutorial"
    customer_dir: "{{ tutorial_dir }}/customer/java/springboot/"
    recommendation_dir: "{{ tutorial_dir }}/recommendation/java/vertx"
    preference_dir: "{{ tutorial_dir }}/preference/java/springboot"
    oc: "/usr/local/bin/oc"
    mvn: "{{ home }}/apache-maven-3.5.4/bin/mvn"
    docker: "/bin/docker"
  tasks:
    - name: Create a destination rule
      shell: |
        {{ istioctl }} replace -f istiofiles/virtual-service-recommendation-v1.yml -n tutorial
      args:
        chdir: "{{ tutorial_dir }}"

